### ISSUE TITLE
Поправить считывание жанров

### ISSUE THREAD

**Issue by HandelSarabande** [Den4t/plugin.video.showday.tv#1]
Было:
`    for g in soup.find('ul', {'class':'subcat'}).findAll('a'):
        for rec in soup.find('select', {'class':'rating'}).findAll('option'):
            if g.text == rec.text.replace('&nbsp;', ''):`

Стало:
`    for g in soup.find('ul', {'class':'cat'}).findAll('a')+soup.find('ul', {'class':'subcat'}).findAll('a'):
        gtext = g.text.encode('utf-8').replace(' года', '')
        for rec in soup.find('select', {'class':'rating'}).findAll('option'):
            rectext = rec.text.encode('utf-8').replace('&nbsp;', '')
            rectext = rectext.replace(' сериалы', '')
            rectext = rectext.replace(' онлайн', '')
            if gtext == rectext:
`

**Comment by Den4t** [comment]
for g in soup.find('ul', {'class':'cat'}).findAll('a') - это не работает нет класса 'cat' на странице.
